### PR TITLE
composer.json file to be used under windows

### PR DESCRIPTION
**Pull request by MedUnes**
changed:
            "./vendor/bin/phing build "
to
            "vendor\\bin\\phing build "

### CODE REVIEW

**Comment by krzysiekpiasecki** [comment]
This PR has broken installation on OS where the directory separator is ```/```.

The way to handle is making installation OS sensible via custom script or using composer exec command.

May I ask you to replace ```vendor\bin\phing build``` with ```composer exec phing build``` and test it on Win. Then try to do a new install.


It should work on Win too.

**Comment by MedUnes** [comment]
I added it as a composer.json.win and not composer.json
So just mention under Windows OS change the file extension and used it for composer installation.
A solution that works at least, IMHO.

**Comment by krzysiekpiasecki** [comment]
Now, I see your point. It should work well, but there is no need to have two composer files for executing build process after vendor installation. 

The solution with `composer exec` command should be a cross compatible, but let me do not close your PR.

**Comment by krzysiekpiasecki** [comment]
At the end two composer files is not a convention. So I'm closing this ticket.

It's related to #53 

@MedUnes  thanks for the contribution.

**Pull request closed without merging**
