### PR TITLE
Integrate KnpMenuBundle 

### PR DESCRIPTION
**Pull request by samrodriguez**
I saw your project and I found it interesting to integrate knpMenu

### CODE REVIEW

**Review by krzysiekpiasecki — COMMENTED** [review]
File ```.gitignore``` must not be locale specific but only a project specific (use .git/info/exclude file to ignore locale NB files)

- Reset .gitignore file
- Remove from index all NB files (/nbproject, ...)

**Review by krzysiekpiasecki — COMMENTED** [review]
Don't manifest dev packages ("knplabs/knp-menu-bundle": "dev-master")

Set stable release.

**Review by krzysiekpiasecki — COMMENTED** [review]
Top right menu modified. See https://gentelella.herokuapp.com

**Review by krzysiekpiasecki — COMMENTED** [review]
Files changed 210 ?

**Review by krzysiekpiasecki — COMMENTED** [review]
Use project CS fixer (from root: ```php vendor/bin/php-cs-fixer fix```)

**Review by krzysiekpiasecki — CHANGES_REQUESTED** [review]
For example: you have removed  ```.php_cs``` configuration file and add cache file. Can you prepare a PR without unnecessary changes like adding web/assets/js/flot/*, etc. Only changes related to MenuBundle and coding standard with project cs fixer. Thanks

**Review by krzysiekpiasecki — CHANGES_REQUESTED** [review]
Tests correct but:

- Standard location for js external libraries is ```web / assets / vendors``` (see .bowerrc file), the installation process supports ```composer build```
- External js libraries files can not be part of the repository. They are installed locally. You need to remove libraries like float, etc. from ```web``` directory.
- The .gitignore file should not contain entries for the local environment. Your IDE files should be ignored locally, eg in an exculde file or in a global .gitignore file.

**Review by krzysiekpiasecki — COMMENTED** [review]
Clear changes. I need a time to review integration, install process and functional tests.

**Review by krzysiekpiasecki — APPROVED** [review]

**Comment by krzysiekpiasecki** [comment]
Can you update a PR and resolve conflicts before merging your changes? Otherwise it must be manually merged.

Accept: project composer.lock, parameters_heroku.yml
Merge: config.yml

It's possible that you get an error with missing parameters_heroku.yml.

**Comment by samrodriguez** [comment]
Done! I updated but  I see conflicts

**Pull request closed without merging**
